remote_theme: "allejo/jekyll-docs-theme"
name: Simple Stuff

links:
    header:
      - title: GitHub
        url: https://github.com/allejo/jekyll-docs-theme
      - title: Page 2
        url: page2
    footer:
      - title: GitHub
        url: https://github.com/allejo/jekyll-docs-theme
      - title: Issues
        url: https://github.com/allejo/jekyll-docs-theme/issues?state=open

ui:
    header:
        color1: "#080331"
        color2: "#673051"
        trianglify: true

social:
    github:
        user: allejo
        repo: jekyll-docs-theme
    twitter:
        enabled: false
        via:
        hash:
        account:
    facebook:
        enabled: false
        profileUrl:

analytics:
    google: UA-123456-1

# Build settings
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock